[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --reuse-db
    --strict-markers
    -ra
markers =
    slow: tests lents (skip avec -m "not slow")
    integration: tests d'intégration
