# Generated by Django 5.1.4 on 2026-07-05 22:36

import uuid
from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=20, unique=True)),
                ("delivery_first_name", models.CharField(max_length=150)),
                ("delivery_last_name", models.CharField(max_length=150)),
                ("delivery_email", models.EmailField(max_length=254)),
                ("delivery_phone", models.CharField(blank=True, max_length=20)),
                ("delivery_street", models.CharField(max_length=255)),
                ("delivery_city", models.CharField(max_length=100)),
                ("delivery_postal_code", models.CharField(max_length=20)),
                (
                    "delivery_country",
                    models.CharField(default="France", max_length=100),
                ),
                ("delivery_date", models.DateField()),
                ("gift_message", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=Decimal("5.99"), max_digits=6),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=8),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("processing", "En préparation"),
                            ("shipped", "Expédiée"),
                            ("delivered", "Livrée"),
                            ("cancelled", "Annulée"),
                            ("refunded", "Remboursée"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("stripe_payment_intent", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Commande",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_name", models.CharField(max_length=255)),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("gift_message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Article de commande",
            },
        ),
    ]
